server:
  port: 8080

spring:
  application:
    name: timchat

  datasource:
    url: jdbc:postgresql://localhost:5432/timchat
    username: timchat
    password: timchat
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: localhost
      port: 6379

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  security:
    user:
      name: admin
      password: admin

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
